// <auto-generated />
using System;
using BoilerplateCore.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BoilerplateCore.Migrations
{
    [DbContext(typeof(BoilerplateCoreDbContext))]
    [Migration("20190327084821_prvaABPmigracijaModeli")]
    partial class prvaABPmigracijaModeli
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.1-servicing-10028")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BoilerplateCore.Models.Kancelarija", b =>
                {
                    b.Property<int>("KancelarijaId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Id");

                    b.Property<string>("Opis");

                    b.HasKey("KancelarijaId");

                    b.ToTable("Kancelarije");
                });

            modelBuilder.Entity("BoilerplateCore.Models.Osoba", b =>
                {
                    b.Property<int>("OsobaId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Id");

                    b.Property<string>("Ime");

                    b.Property<int>("KancelarijaId");

                    b.Property<string>("Prezime");

                    b.HasKey("OsobaId");

                    b.HasIndex("KancelarijaId");

                    b.ToTable("Osobe");
                });

            modelBuilder.Entity("BoilerplateCore.Models.Uredjaj", b =>
                {
                    b.Property<int>("UredjajId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ImeUredjaja");

                    b.HasKey("UredjajId");

                    b.ToTable("Uredjaji");
                });

            modelBuilder.Entity("BoilerplateCore.Models.UredjajUzetVracen", b =>
                {
                    b.Property<int>("UredjajUzetVracenId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("OsobaId");

                    b.Property<int>("UredjajId");

                    b.Property<DateTime>("Uzet");

                    b.Property<DateTime?>("Vracen");

                    b.HasKey("UredjajUzetVracenId");

                    b.HasIndex("OsobaId");

                    b.HasIndex("UredjajId");

                    b.ToTable("UredjajUzetVraceni");
                });

            modelBuilder.Entity("BoilerplateCore.Models.Osoba", b =>
                {
                    b.HasOne("BoilerplateCore.Models.Kancelarija", "Kancelarija")
                        .WithMany("Osobe")
                        .HasForeignKey("KancelarijaId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("BoilerplateCore.Models.UredjajUzetVracen", b =>
                {
                    b.HasOne("BoilerplateCore.Models.Osoba", "Osoba")
                        .WithMany("UzetiUredjaji")
                        .HasForeignKey("OsobaId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("BoilerplateCore.Models.Uredjaj", "Uredjaj")
                        .WithMany()
                        .HasForeignKey("UredjajId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
